# Generated by Django 5.0.1 on 2024-02-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='card_number',
            field=models.CharField(default='', max_length=150),
        ),
    ]
