# Generated by Django 5.0.1 on 2024-01-25 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Product Image')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_message', models.TextField(verbose_name='Message')),
                ('reviews_giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default=None, max_length=100)),
                ('user_image', models.ImageField(upload_to='product_images/user', verbose_name='Product user Image')),
                ('product_token', models.CharField(blank=True, db_index=True, default=None, max_length=200, null=True)),
                ('product_title', models.CharField(db_index=True, default=None, max_length=150)),
                ('product_description', models.TextField(default=None, verbose_name='Product Description')),
                ('condition', models.CharField(default='Not decided', max_length=20, verbose_name='Condition')),
                ('brand', models.CharField(db_index=True, default='Not decided', max_length=100, verbose_name='Brand')),
                ('color', models.CharField(default=None, max_length=100)),
                ('model', models.CharField(default=None, max_length=100)),
                ('ram', models.CharField(default=None, max_length=100)),
                ('storage', models.BigIntegerField(default=0)),
                ('battery_capacity', models.CharField(default=None, max_length=20)),
                ('price', models.IntegerField(default=None)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product_image', models.ManyToManyField(blank=True, related_name='products_images', to='core.productimage')),
                ('username', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Products',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activate_order', models.BooleanField(db_index=True, default=False)),
                ('received_order', models.BooleanField(db_index=True, default=False)),
                ('canceled_order', models.BooleanField(db_index=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userproducts')),
            ],
        ),
        migrations.CreateModel(
            name='FavouritesSaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_products', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.userproducts')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_info', models.CharField(choices=[('cash', 'Cash'), ('Google pay', 'Google pay')], db_index=True, default='Not decided', max_length=100)),
                ('fav_saved_items', models.ManyToManyField(blank=True, related_name='user_saved', to='core.favouritessaved')),
                ('my_ads', models.ManyToManyField(blank=True, related_name='user_ads', to='core.userproducts')),
                ('orders', models.ManyToManyField(blank=True, related_name='user_orders', to='core.order')),
                ('reviews', models.ManyToManyField(blank=True, related_name='user_reviews', to='core.reviews')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
