# Generated by Django 5.0.1 on 2024-01-25 08:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducts',
            name='user_image',
            field=models.ImageField(default=core.models.UserProducts.default_user_image, upload_to='product_images/user', verbose_name='Product user Image'),
        ),
    ]
