# Generated by Django 5.0.1 on 2024-01-25 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userproducts_user_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favouritessaved',
            options={'ordering': ['-saved_at'], 'verbose_name': 'Favorite Saved', 'verbose_name_plural': 'Favorites Saved'},
        ),
        migrations.AlterField(
            model_name='favouritessaved',
            name='saved_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='favouritessaved',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
