# Generated by Django 5.0.1 on 2024-02-05 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_userproducts_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sold_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
