# Generated by Django 5.0.1 on 2024-01-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_favouritessaved_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='activate_order',
            field=models.CharField(db_index=True, default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='canceled_order',
            field=models.CharField(db_index=True, default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='received_order',
            field=models.CharField(db_index=True, default=False, max_length=100),
        ),
    ]
