# Generated by Django 5.0.1 on 2024-01-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_activate_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchased_quantity',
            field=models.IntegerField(db_index=True, default=None),
        ),
    ]
