# Generated by Django 5.0.1 on 2024-01-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_account_userproducts_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducts',
            name='battery_capacity',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='brand',
            field=models.CharField(blank=True, choices=[('Nokia', 'Nokia'), ('Iphone', 'Iphone'), ('Sumsung', 'Sumsung'), ('Opps', 'Opps'), ('Vivo', 'Vivo')], db_index=True, default='Not decided', max_length=20, null=True, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='condition',
            field=models.CharField(blank=True, choices=[('New with tags', 'New with tags'), ('New without tags', 'New without tags'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory')], db_index=True, default='Not decided', max_length=20, null=True, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='model',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='product_description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Product Description'),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='ram',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='storage',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
