# Generated by Django 5.0.1 on 2024-02-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_is_blocked_alter_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='purchased_quantity',
        ),
        migrations.AddField(
            model_name='userproducts',
            name='notification_token',
            field=models.CharField(db_index=True, default=False, max_length=200),
        ),
    ]
