# Generated by Django 5.0.1 on 2024-01-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userproducts_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducts',
            name='battery_capacity',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='brand',
            field=models.CharField(choices=[('Nokia', 'Nokia'), ('Iphone', 'Iphone'), ('Sumsung', 'Sumsung'), ('Opps', 'Opps'), ('Vivo', 'Vivo')], db_index=True, default='Not decided', max_length=20, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='color',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='condition',
            field=models.CharField(choices=[('New with tags', 'New with tags'), ('New without tags', 'New without tags'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory')], default='Not decided', max_length=20, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='model',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='product_description',
            field=models.TextField(default=None, verbose_name='Product Description'),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='product_title',
            field=models.CharField(db_index=True, default=None, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='product_token',
            field=models.CharField(db_index=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='ram',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='storage',
            field=models.BigIntegerField(default=0),
        ),
    ]
