# Generated by Django 5.0.1 on 2024-02-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_order_purchased_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='address2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(db_index=True, default=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(db_index=True, default=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='latitude1',
            field=models.CharField(db_index=True, default=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='latitude2',
            field=models.CharField(db_index=True, default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Info_user',
        ),
    ]
