# Generated by Django 5.0.1 on 2024-01-26 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_at_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_at_product', to='core.userproducts'),
        ),
    ]
