# Generated by Django 5.0.1 on 2024-02-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_userproducts_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducts',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
