# Generated by Django 5.0.1 on 2024-01-27 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_message_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, default=False, max_length=100)),
                ('country', models.CharField(db_index=True, default=False, max_length=100)),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('postal_code', models.IntegerField(default=0)),
                ('latitude1', models.CharField(db_index=True, default=False, max_length=100)),
                ('latitude2', models.CharField(db_index=True, default=False, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
