# Generated by Django 5.0.1 on 2024-01-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_info_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_user',
            name='address2',
            field=models.TextField(null=True),
        ),
    ]
